# Generated by Django 2.0.6 on 2020-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_bulbstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_reading',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_reading', models.CharField(blank=True, default='', max_length=255)),
                ('humidity_reading', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
